sudo: required
services:
  - docker

before_install:
  - docker build -t kevinmui/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kevinmui/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-2-054115631216"
  bucket_path: "docker-react"
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  on:
    branch: main